# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9a407cf6e4ca53d31eb044542f058560e6808ffbcdb723b77bc9a8709db20a920417510b3154d0591657a19a4920a01c2f71f66543dee189f0bd20cb2246bd9

test:
  secret_key_base: 42fc9e845e4209b4964fea260fbc762f83fe8ec1a08679952a0b53a12aa557ad38c3fe02828b4d61fbaa6412af0cb308e1b62dd3759c20bb06b0a5c8f79a4a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
